CREATE TABLE books
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    isbn      VARCHAR(13)                             NOT NULL,
    title     VARCHAR(255)                            NOT NULL,
    author    VARCHAR(255)                            NOT NULL,
    publisher VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_books PRIMARY KEY (id)
);

ALTER TABLE books
    ADD CONSTRAINT uc_books_isbn UNIQUE (isbn);